# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SQLPopVC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SQLPopVC'
  # Pods for SQLPopVC

  target 'SQLPopVCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SQLPopVCUITests' do
    # Pods for testing
  end

end
